### ISSUE TITLE
Why not exclude the Script grammer target?

### ISSUE THREAD

**Issue by allenwb** [endojs/Jessie#12]
Wonder why you appear to allow legacy Scripts when you could  say that only the Module top level sematics is supported. 

The primary difference between a script and a module with no import/export is implicit strict mode, top level declaration are module scopes, and top level this is undefined. Those all seem like desirable  characteristics and having only a single kind of top level code unit seems like  a significant  simplification.

**Comment by erights** [comment]
Hi @allenwb , thanks for the suggestion. This seems like a good idea. Will close once I've revised the text.

**Comment by erights** [comment]
The grammar does not yet include export and import. See https://github.com/Agoric/Jessie/issues/8

**Comment by erights** [comment]
@allenwb , We've decided to take your suggestion. Once we support modules well in the ses-shim (attn @michaelfig ), we'll be able to close this.

**Comment by michaelfig** [comment]
Done.
