### ISSUE TITLE
Module exports?

### ISSUE THREAD

**Issue by dckc** [endojs/Jessie#8]
I have all but the last line of makeAlice.js working. This doesn't parse:

```
module.exports = makeAlice;
```

A comment explains that this is on purpose.

An example you sent me uses `export function ...` but I don't see that in the TineSES grammar.

p.s. https://github.com/dckc/tinyses2rho/blob/master/src/test/resources/makeAlice.js 6572f13 shows the changes I made to constrain makeAlice.js to TinySES:
- makeAlice: var -> const / let; `cancel` needs initializer

**Comment by erights** [comment]
We should add a carefully chosen subset of the ES module export/import syntax at http://www.ecma-international.org/ecma-262/9.0/#sec-imports to the TinySES grammar. How about we allow only default import and export, which  
   * avoid the visibility of the exotic module object,
   * exports only values, not live bindings
   * avoids temporal dead zone of exported live bindings
   * reduces the issue of top-level mutable state to the presence of mutable state in the exported value

Perhaps something like

```
importDecl ::= "import" defVar "from" STRING ";"
exportDecl ::= "export" "default" exportableExpr ";"
exportableExpr ::=
  ("function" / "async" / "class")               ${() => FAIL}
/ expr;
```

Attn @warner

**Comment by dckc** [comment]
Are the things you want to export expressions? They seem more like declarations. So perhaps `exportableDecl` rather than `exportableExpr`? Wait... I guess I'm reading it backwards... you want to **exclude** `export function ...`? Now I'm really lost.

What are you suggesting goes in makeAlice.js?

Are you really suggesting that `export default 1;` is a declaration in the TinySES language?

**Comment by erights** [comment]
> Are the things you want to export expressions?

For TinySES, yes, that is what I am suggesting.

> They seem more like declarations. So perhaps exportableDecl rather than exportableExpr? Wait... I guess I'm reading it backwards... you want to exclude export function ...? Now I'm really lost.

Correct, I am excluding the things excluded by the lookahead of the last clause of ExportDeclaration at http://www.ecma-international.org/ecma-262/9.0/#sec-exports , since I only what to export an expression while staying within a subset of the ES grammar.

> What are you suggesting goes in makeAlice.js?

```js
import Q from 'q';
import escrowExchange from './escrowExchange';
import cajaVM from './cajaVM';

function makeAlice(...) {...}

export default def(makeAlice);
```

If we wanted to write instead something like

```js
export function makeAlice(...) {...}
```

which is much more idiomatic JS style, we'd have no natural way to `def` (transitively tamper-proof the API surface) the `makeAlice` function before it becomes available to others.


> Are you really suggesting that `export default 1;` is a declaration in the TinySES language?

Yes. It declares that the module exports (as its default value) the value 1. 

Since TinySES includes records and record patterns, we can effectively export a set of named declarations by instead exporting, as the module's default export value, a `def`ed record with those field names. IOW, rather than

```js
export function foo(...) {...}
export const bar = 8;
```
```js
import {foo, bar} from 'x.js';
```
we would instead write
```js
function foo(...) {...}
const bar = 8;
export default def({foo, bar});
```
```js
import mx from 'x.js';
const {foo, bar} = mx;
```
Admittedly, it is weird that we now need to invent the name `mx` rather than putting the record pattern directly in the import declaration. That is indeed an awkward notational price of this suggestion.

**Comment by erights** [comment]
Another downside of this suggestion is that it cannot express cyclic module dependencies.

**Comment by erights** [comment]
TinySES modules should be statically constrained (by post-parse static checks) from doing anything imperative at top level. Outcomes are independent of the order modules are evaluated. Given these simplifying assumptions, default export/import has a trivial translation to commonjs modules:

```js
import Q from 'q';
import escrowExchange from './escrowExchange';
import cajaVM from './cajaVM';

function makeAlice(...) {...}

export default def(makeAlice);
```
is equivalent enough to

```js
const Q = require("q");
const escrowExchange = require("./escrowExchange");
const cajaVM = require("./cajaVM");

function makeAlice(...) {...}

module.exports = def(makeAlice);
```

**Comment by dckc** [comment]
> `export default def(makeAlice);`

Ah. Now I see.

> it cannot express cyclic module dependencies

I don't see why not. I suppose if I studied the ES specs more closely I would learn why not, but...

It looks an awful lot like what we did in Monte; while the implementation of _resolving_ the circular dependencies hurts my head, it's similar to other knot-tying techniques with promises and seems to work well enough.

**Comment by dckc** [comment]
I'm not sure, but reportedly the jspm designers figured it out.

https://blog.angular-university.io/introduction-to-es6-modularity-the-jspm-package-manager-and-the-systemjs-loader/

**Comment by michaelfig** [comment]
Hi, I'm needing some clarification to understand more fully what legal `import` semantics is for Jessie modules.

My current approach is to parse the module, recording the expression that exists in `export default EXPR`.  However, evaluating EXPR has to happen sooner or later, and that means we may see ordering differences when loading modules!

Supporting a recursive implementation of `import` (separate load/parse and instantiate phases) is not really any harder than the other compiler infrastructure that is needed for Jessie.  For bootstrapping I'm snarfing import/export from `--experimental-modules` and *.mjs source files (node.js 8.5+ supports ES Modules).

Here's what I'd consider a basic recursive module implementation in an environment that doesn't need to export to the world.

```javascript
// makeAlice.js below:
_defModule(['q', './escrowExchange', './cajaVM'], _instantiate => {
    // Can't use const here, or else we cannot "tie the knot".
    let Q, escrowExchange, cajaVM;

    function makeAlice(...) {...}

    // Run the export thunk after the imports are loaded.
    _instantiate(_imports => [Q, escrowExchange, cajaVM], () => def(makeAlice)));
  });
```

And the import/export infrastructure can be stubbed like this:
```javascript
  function doLoad(mname, loader) {
     // Look up the loading promise in a cache somewhere.
     _loadingPromise[mname] = _loadingPromise[mname] || [false, loader]:
     return loaded.then([once, exportVal] => {
       if (!once) {
         // Update the promise in the cache with our thunk.
         exportVal = exportVal();
         _loadingPromise[mname] = Promise.resolve([true, exportVal]);
       }
       return exportVal;
     });
  }

function _defModule(mname, imports, loader) {
  const loading = imports.map((mod) => doLoad(mod, () => require(mod));

  // The instantiation semantics: when we're done loading, import, then export (instantiate).
  loader((_importer, _exporter) => {
    const loadSelf = doLoad(mname, () => Promise.all(loading).then(_importer).then(_exporter));
    return Promise.all(loading)
      .then(_importer).then(() => {
     ;
    if (
    if (_loadingPromise[mname]) {
     return;
    }
    _loadingPromise[mname] = Promise.resolve([false, _exporter]);
    Promise.all(loading).then(_importer).then(() => {
      if (_loadingPromise[mname]_exporter);
  });
  return loader;
}
```

**Comment by michaelfig** [comment]
Implemented.
